---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
spec:
  replicas: 1  # Ensuring there are multiple pods for redundancy
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: bhoomika2897n/frontend:v1  # Corrected image name spelling
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 80     # Port on the service
      targetPort: 80 # Port on the pod
      #nodePort: 30081  # Exposing via NodePort (optional, must be between 30000-32767)
