apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendservice-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendservice-1
  template:
    metadata:
      labels:
        app: backendservice-1
    spec:
      containers:
        - name: backendservice-1-cont
          image: bhoomika2897n/nodejsservice-1:latest  # Replace with actual image, e.g. bhoomika2897n/backendservice-1:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backendservice-1
spec:
  selector:
    app: backendservice-1
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081  # Optional: you can omit this to let Kubernetes assign a port
