pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "bhoomika2897n/frontend-service:${BUILD_NUMBER}"
        DOCKER_CREDENTIALS_ID = "Docker_cred"
    }

    tools {
        nodejs 'node' // Defined in Jenkins > Global Tool Configuration
    }

    stages {
        stage('Print Node Version') {
            steps {
                bat 'node -v'
            }
        }

        stage('Clone Git Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/bhoomikakrish/Frontend_Service.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('react_project/frontend_service_1') {
                    bat 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('react_project/frontend_service_1') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('react_project/frontend_service_1') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('react_project/frontend_service_1') {
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', DOCKER_CREDENTIALS_ID) {
                            dockerImage.push()
                            dockerImage.push("latest")
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying ${DOCKER_IMAGE}"
                // Add your deploy logic here (e.g., kubectl apply or docker run)
            }
        }
    }

    post {
        success {
            echo 'Deployment succeeded!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
