pipeline {
    agent any

        tools {
        nodejs 'node'
    }
    
    environment {
        DOCKER_IMAGE = "bhoomika2897n/frontend-service:$BUILD_NUMBER"
        DOCKER_CREDENTIALS_ID = "Docker_cred"
    }
    stages {
        stage('Print Node Version') {
            steps {
                bat 'node -v'
            }
        }

        stage('Clone Git Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/bhoomikakrish/Frontend_Service.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('react_project/frontend_service_1') {
                    bat 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('react_project/frontend_service_1') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('nodejs_project/Backend-Services/nodejs_project_1') {
                    script {
                        docker.withRegistry('', "${DOCKER_CREDENTIALS_ID}") {
                            def app = docker.build("${IMAGE_NAME}")
                            app.push()
                            app.push("latest")
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying ${DOCKER_IMAGE}"
                // kubectl apply -f deployment.yaml or similar
            }
        }
    }

    post {
        success {
            echo 'Deployment succeeded!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
