pipeline {
    agent any

    tools {
        nodejs 'node'
    }

    environment {
        IMAGE_NAME = "bhoomika2897n/frontendimage:$BUILD_NUMBER"
        DOCKER_CREDENTIALS_ID = "Docker_cred"
    }

    stages {
        stage('Print Node Version') {
            steps {
                bat 'node -v'
            }
        }

        stage('Clone Git Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/bhoomikakrish/Frontend_Service.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('react_project/frontend_service_1') {
                    bat 'npm install -g npm-check-updates'
                    bat 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('react_project/frontend_service_1') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir('react_project/frontend_service_1') {
                    script {
                       docker.withRegistry('', "${DOCKER_CREDENTIALS_ID}") {
                            def app = docker.build("${IMAGE_NAME}")
                            app.push()
                            app.push("latest")
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying ${DOCKER_IMAGE}"
                // Uncomment and configure the below line if you want to deploy using Kubernetes
                // bat 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
}

    post {
        success {
            echo 'Deployment succeeded!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
