pipeline {
    agent any

    tools {
        nodejs 'node' // Must match what's configured in Jenkins > Global Tool Configuration
    }

    environment {
        IMAGE_NAME = "bhoomika2897n/nodejsservice-2"
        DOCKER_CREDENTIALS_ID = "docker-cred"
    }

    parameters {
        choice(
            name: 'Branch_Name',
            choices: ['main', 'master'],
            description: 'Please select branch name'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.Branch_Name}", url: 'https://github.com/bhoomikakrish/Practice--Projects.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('nodejs_project/Backend-Services/nodejs_project_1') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('nodejs_project/Backend-Services/nodejs_project_1') {
                    script {
                        docker.withRegistry('', "${DOCKER_CREDENTIALS_ID}") {
                            def app = docker.build("${IMAGE_NAME}")
                            app.push("latest")
                        }
                    }
                }
            }
        }
    }
}
